### ISSUE TITLE
Методы API

### ISSUE THREAD

**Issue by Anatoliyphp** [m3tro1d/backend#6]
https://github.com/m3tro1d/backend/blob/262f2e47699f365dd57d0f8ab6b6f79acb0953f6/labs/ScrumBoard/WebScrumBoard/Controllers/ScrumBoardController.cs#L27

Названия методов нужно поправить, сейчас интуитивно не понятно, какой метод и что делает

**Comment by m3tro1d** [comment]
Немного не понял, как можно еще назвать метод помимо его непосредственного названия, как тут:

https://github.com/m3tro1d/backend/blob/262f2e47699f365dd57d0f8ab6b6f79acb0953f6/labs/ScrumBoard/WebScrumBoard/Controllers/ScrumBoardController.cs#L27-L28

**Comment by Anatoliyphp** [comment]
Например в данном методе мы получаем список досок следовательно название - GetBoards, тоже самое в маршруте. ListBoards переводится как список досок, так модно было бы назвать переменную, но не метод. Название метода как и самой api должно говорить о том, что он делает

**Comment by m3tro1d** [comment]
@Anatoliyphp привык именовать методы получения как ListSomething от глагола to list :) Но т.к. в данном случае принципиально, поправил.
